services:
  db:
    image: postgres:17
    container_name: gold_db
    restart: always
    env_file: ./backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gold_backend
    restart: always
    env_file: ./backend/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db