"""Add missing columns to operating_log

Revision ID: 0bf7e114c69a
Revises: 27e263602ff4
Create Date: 2026-02-02 14:20:57.205088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bf7e114c69a'
down_revision: Union[str, Sequence[str], None] = '27e263602ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operating_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('operating_log', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('operating_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_operating_log_created_at'), 'operating_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_operating_log_id'), 'operating_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operating_log_id'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_created_at'), table_name='operating_log')
    op.alter_column('operating_log', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('operating_log', 'updated_at')
    op.drop_column('operating_log', 'created_at')
    # ### end Alembic commands ###
