"""init tables

Revision ID: 3fb06ff304ec
Revises: 
Create Date: 2026-01-27 20:10:46.754271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fb06ff304ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('invested_krw', sa.Float(), nullable=False),
    sa.Column('equity_krw', sa.Float(), nullable=False),
    sa.Column('pnl_krw', sa.Float(), nullable=False),
    sa.Column('pnl_rate', sa.Float(), nullable=False),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_base_date'), 'portfolio_snapshots', ['base_date'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_created_at'), 'portfolio_snapshots', ['created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_portfolio_snapshots_created_at'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_base_date'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
