"""
Revision ID: 5444bf8c085b
Revises:
Create Date: 2026-03-04 09:16:18.458731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5444bf8c085b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'operating_log' not in tables:
        op.create_table('operating_log',
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('event_name', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_logs_category_timestamp', 'operating_log', ['category', 'timestamp'], unique=False)
        op.create_index('ix_logs_level_timestamp', 'operating_log', ['level', 'timestamp'], unique=False)
        op.create_index(op.f('ix_operating_log_category'), 'operating_log', ['category'], unique=False)
        op.create_index(op.f('ix_operating_log_created_at'), 'operating_log', ['created_at'], unique=False)
        op.create_index(op.f('ix_operating_log_event_name'), 'operating_log', ['event_name'], unique=False)
        op.create_index(op.f('ix_operating_log_id'), 'operating_log', ['id'], unique=False)
        op.create_index(op.f('ix_operating_log_level'), 'operating_log', ['level'], unique=False)
        op.create_index(op.f('ix_operating_log_timestamp'), 'operating_log', ['timestamp'], unique=False)

    if 'portfolio_snapshots' not in tables:
        op.create_table('portfolio_snapshots',
        sa.Column('base_date', sa.Date(), nullable=False),
        sa.Column('invested_krw', sa.Float(), nullable=False),
        sa.Column('equity_krw', sa.Float(), nullable=False),
        sa.Column('pnl_krw', sa.Float(), nullable=False),
        sa.Column('pnl_rate', sa.Float(), nullable=False),
        sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('base_date', name='uq_portfolio_snapshots_base_date')
        )
        op.create_index(op.f('ix_portfolio_snapshots_base_date'), 'portfolio_snapshots', ['base_date'], unique=False)
        op.create_index(op.f('ix_portfolio_snapshots_created_at'), 'portfolio_snapshots', ['created_at'], unique=False)
        op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)

    if 'trade_history' not in tables:
        op.create_table('trade_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('market', sa.String(length=20), nullable=False),
        sa.Column('side', sa.String(length=10), nullable=False),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('fee', sa.Float(), nullable=False),
        sa.Column('strategy', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_trade_history_id'), 'trade_history', ['id'], unique=False)
        op.create_index(op.f('ix_trade_history_market'), 'trade_history', ['market'], unique=False)
        op.create_index('ix_trade_history_market_timestamp', 'trade_history', ['market', 'timestamp'], unique=False)
        op.create_index(op.f('ix_trade_history_timestamp'), 'trade_history', ['timestamp'], unique=False)

    if 'users' not in tables:
        op.create_table('users',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trade_history_timestamp'), table_name='trade_history')
    op.drop_index('ix_trade_history_market_timestamp', table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_market'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_id'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_created_at'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_base_date'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_operating_log_timestamp'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_level'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_id'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_event_name'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_created_at'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_category'), table_name='operating_log')
    op.drop_index('ix_logs_level_timestamp', table_name='operating_log')
    op.drop_index('ix_logs_category_timestamp', table_name='operating_log')
    op.drop_table('operating_log')
    # ### end Alembic commands ###
