"""create trade_history table

Revision ID: 90e03a5ab8e1
Revises: fix_snapshot_defaults
Create Date: 2026-02-24 06:58:57.682663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90e03a5ab8e1'
down_revision: Union[str, Sequence[str], None] = 'fix_snapshot_defaults'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_history_id'), 'trade_history', ['id'], unique=False)
    op.create_index(op.f('ix_trade_history_market'), 'trade_history', ['market'], unique=False)
    op.create_index('ix_trade_history_market_timestamp', 'trade_history', ['market', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trade_history_timestamp'), 'trade_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_timestamp'), table_name='trade_history')
    op.drop_index('ix_trade_history_market_timestamp', table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_market'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_id'), table_name='trade_history')
    op.drop_table('trade_history')
    # ### end Alembic commands ###
