"""create trade history table

Revision ID: c501f51fff24
Revises: 90e03a5ab8e1
Create Date: 2026-02-25 07:05:45.772611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c501f51fff24'
down_revision: Union[str, Sequence[str], None] = '90e03a5ab8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operating_log', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('ix_logs_category_timestamp', 'operating_log', ['category', 'timestamp'], unique=False)
    op.create_index('ix_logs_level_timestamp', 'operating_log', ['level', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_level_timestamp', table_name='operating_log')
    op.drop_index('ix_logs_category_timestamp', table_name='operating_log')
    op.alter_column('operating_log', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
