"""create operating_log table

Revision ID: d669d3fd285d
Revises: 27e263602ff4
Create Date: 2026-02-04 14:48:35.497696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd669d3fd285d'
down_revision: Union[str, Sequence[str], None] = '27e263602ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_log',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_log_category'), 'operating_log', ['category'], unique=False)
    op.create_index(op.f('ix_operating_log_created_at'), 'operating_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_operating_log_event_name'), 'operating_log', ['event_name'], unique=False)
    op.create_index(op.f('ix_operating_log_id'), 'operating_log', ['id'], unique=False)
    op.create_index(op.f('ix_operating_log_level'), 'operating_log', ['level'], unique=False)
    op.create_index(op.f('ix_operating_log_timestamp'), 'operating_log', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_portfolio_snapshots_base_date', 'portfolio_snapshots', ['base_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_portfolio_snapshots_base_date', 'portfolio_snapshots', type_='unique')
    op.drop_index(op.f('ix_operating_log_timestamp'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_level'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_id'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_event_name'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_created_at'), table_name='operating_log')
    op.drop_index(op.f('ix_operating_log_category'), table_name='operating_log')
    op.drop_table('operating_log')
    # ### end Alembic commands ###
